-- 1
SELECT * FROM IA_PAISES.ANALYTICS.VW_AI_KPI
WHERE COUNTRY_ID = 'USA'
ORDER BY YEAR;

-- 2
SELECT INDICATOR, COUNT(*), MIN(YEAR), MAX(YEAR)
FROM RAW.WORLDBANK_INDICATORS
GROUP BY INDICATOR;

-- por si fallan al cargar
USE DATABASE IA_PAISES;
TRUNCATE TABLE RAW.OPENALEX_PUBLICATIONS;
TRUNCATE TABLE RAW.BIGQUERY_PATENTS;