CREATE OR REPLACE VIEW IA_PAISES.ANALYTICS.VW_AI_KPI AS
SELECT
    COUNTRY_ID,
    COUNTRY_NAME,
    YEAR,
    MAX(CASE WHEN INDICATOR = 'AI_PUBLICATIONS' THEN VALUE END)        AS AI_PUBLICATIONS,
    MAX(CASE WHEN INDICATOR = 'AI_PATENTS' THEN VALUE END)             AS AI_PATENTS,
    MAX(CASE WHEN INDICATOR = 'POPULATION' THEN VALUE END)             AS POPULATION,
    MAX(CASE WHEN INDICATOR = 'GDP_USD' THEN VALUE END)                AS GDP_USD,
    MAX(CASE WHEN INDICATOR = 'GDP_PER_CAPITA_USD' THEN VALUE END)     AS GDP_PER_CAPITA_USD,
    MAX(CASE WHEN INDICATOR = 'RD_GDP_PCT' THEN VALUE END)             AS RD_GDP_PCT,
    MAX(CASE WHEN INDICATOR = 'RESEARCHERS_PER_MILLION' THEN VALUE END) AS RESEARCHERS_PER_MILLION
FROM (
    SELECT * FROM IA_PAISES.RAW.OPENALEX_PUBLICATIONS
    UNION ALL
    SELECT * FROM IA_PAISES.RAW.WORLDBANK_INDICATORS
    UNION ALL
    SELECT * FROM IA_PAISES.RAW.BIGQUERY_PATENTS
)
GROUP BY COUNTRY_ID, COUNTRY_NAME, YEAR;