USE ROLE ACCOUNTADMIN;

-- 1. BBDD
CREATE DATABASE IF NOT EXISTS IA_PAISES;
USE DATABASE IA_PAISES;

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS IA_PAISES.RAW;
CREATE SCHEMA IF NOT EXISTS IA_PAISES.ANALYTICS;

-- 3. Tablas RAW (drop + create)
DROP TABLE IF EXISTS IA_PAISES.RAW.OPENALEX_PUBLICATIONS;
CREATE TABLE IA_PAISES.RAW.OPENALEX_PUBLICATIONS (
    COUNTRY_ID   VARCHAR(10),
    COUNTRY_NAME VARCHAR(100),
    YEAR         INT,
    INDICATOR    VARCHAR(50),
    VALUE        FLOAT
);

DROP TABLE IF EXISTS IA_PAISES.RAW.WORLDBANK_INDICATORS;
CREATE TABLE IA_PAISES.RAW.WORLDBANK_INDICATORS (
    COUNTRY_ID   VARCHAR(20),
    COUNTRY_NAME VARCHAR(100),
    YEAR         INT,
    INDICATOR    VARCHAR(50),
    VALUE        FLOAT
);

DROP TABLE IF EXISTS IA_PAISES.RAW.BIGQUERY_PATENTS;
CREATE TABLE IA_PAISES.RAW.BIGQUERY_PATENTS (
    COUNTRY_ID   VARCHAR(10),
    COUNTRY_NAME VARCHAR(100),
    YEAR         INT,
    INDICATOR    VARCHAR(50),
    VALUE        FLOAT
);

SHOW TABLES IN SCHEMA IA_PAISES.RAW;